### ISSUE TITLE
Request a dataset

### ISSUE THREAD

**Issue by vivienne1221** [ErolCitak/SarOpticImageMatching#1]
I recently came across your paper titled [Visual_Saliency_Aided_SAR_and_Optical_Image_Matching]  found it to be a valuable contribution to the field.

I am currently working on a related research project and believe that the dataset used in your paper would greatly benefit my study.  And you reached to sen1-2 dataset’s authors to obtain their original validation split.I would be grateful if you could provide me with access to the dataset mentioned in your paper. Obtaining this dataset would enable me to conduct a more comprehensive analysis and validate the findings of your research.

 I look forward to your favorable response and appreciate your willingness to contribute to the advancement of knowledge in our field.

**Comment by ErolCitak** [comment]
Hi, of course, there are the official links;

**Dataset download link**; https://mediatum.ub.tum.de/1436631
Under the "Technical remarks" section, the authors provide several options to download the dataset.

Besides that, as you have already known that used patches in training/validation and testing matters too much. So I'm also attaching to these patch names in this repo so you can use them in your work for comparison purposes.

**Comment by vivienne1221** [comment]
thank you so much.
